name: Generate snake game

on:
  schedule: # executar a cada 12 horas
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs para atualizar dados
    runs-on: ubuntu-latest
    steps:
      # Animação da Cobrinha
      - uses: Sutil/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake2.svg
          snake_color: 'blue'

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
